asdasd

diff --git a/.github/workflows/pulls.yaml b/.github/workflows/pulls.yaml
--- a/.github/workflows/pulls.yaml
+++ b/.github/workflows/pulls.yaml
@@ -1,17 +1,21 @@
 name: Check PR
 
 on:
-  pull_request:
+  pull_request_target:
 
 jobs:
   check-sign-off:
     name: Write comment if unsigned commits found
-    env:
-      FORCE_COLOR: 1
     runs-on: ubuntu-latest
     permissions:
       contents: read
       pull-requests: write
     steps:
-      # - uses: live627/check-pr-signoff-action@v1.0.0
       - uses: cloudforet-io/check-pr-action@v1
+        id: review
+      # fail the "check" if review is negative
+      - name: Notify Result
+        if: ${{ steps.review.outputs.signedoff == 'false' }}
+        run: |
+          echo "The DCO signoff is missing"
+          exit 1
